[package]
name = "permutation_compression"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
lazy_static = "1.5.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"

[dev-dependencies]
rand = "0.9.0"
